openapi: 3.0.0
info:
  title: WEBSERVICE-NODE-PESSOA
  description: API para Entidades com Node.js e TypeORM
  version: 1.0.0

paths:
  /pessoa:
    $ref: './paths/pessoa.yaml'
  /pessoa/{id}:
    $ref: './paths/pessoaById.yaml'

components:
  schemas:
    Pessoa:
      $ref: './schemas/pessoa.yaml'
    ErrorResponse:
      $ref: './schemas/errorResponse.yaml'
  responses:
    $ref: './responses.yaml'
  securitySchemes: 
    $ref: './security.yaml'
